# Generated by Django 3.1.7 on 2021-03-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField()),
                ('rating', models.CharField(blank=100, max_length=2)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
