# Generated by Django 3.1.7 on 2021-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('url', models.URLField()),
                ('years', models.IntegerField(default=0)),
                ('actor_list', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
