# Generated by Django 3.1.7 on 2021-02-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(blank=100, max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='years',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
