# Generated by Django 3.1.7 on 2021-02-27 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210226_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor_list',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='years',
        ),
    ]
